export type TaskStatus = 'CREATED' | 'RUNNING' | 'COMPLETED' | 'COMPLETED_WITH_WARNINGS' | 'PARTIALLY_COMPLETED' | 'FAILED' | 'CANCELLED';
export type StepStatus = 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'SKIPPED';
export type PageRole = 'COVER' | 'TABLE_OF_CONTENTS' | 'AD_SECTION_TEXT' | 'RUNWAY_DATA' | 'NAVAID_DATA' | 'WAYPOINT_COORDINATE_TABLE' | 'PROCEDURE_INDEX' | 'SID_CHART' | 'STAR_CHART' | 'APPROACH_CHART' | 'PROCEDURE_TABLE' | 'MINIMA_TABLE' | 'PROFILE_VIEW' | 'GENERAL_PROCEDURE_NOTES' | 'OBSTACLE_DATA' | 'AERODROME_CHART' | 'UNKNOWN';
export type FieldStatus = 'CONFIRMED' | 'DERIVED' | 'AI_INFERRED' | 'CONFLICTED' | 'UNRESOLVED' | 'MANUALLY_EDITED';

export interface PageEvidence { evidenceId: string; documentId?: string | null; pageNumber: number; sourceType: string; bbox?: [number, number, number, number]; rawText?: string; imageCropPath?: string | null; extractionMethod: 'NATIVE_TEXT' | 'OCR' | 'VISION' | 'DERIVED'; confidence: number; modelCallId?: string | null; planAction?: string | null }
export interface PageAsset { documentId?: string; fileName?: string; pageNumber: number; globalPageNumber?: number; width: number; height: number; rotation: number; renderedImagePath: string; thumbnailPath: string; nativeText: string; textSpans: Array<{ text: string; bbox: [number, number, number, number] }>; vectorPaths: Array<{ operator: string; args?: number[] }>; vectorPathCount?: number; embeddedImages: Array<Record<string, unknown>>; detectedTables: Array<Record<string, unknown>>; detectedLanguages: string[]; quality: { isScanned: boolean; nativeTextCoverage: number; renderDpi: number; garbledTextRatio?: number; transcribed?: boolean }; summary: string; title?: string }
export interface PageRoleResult { pageNumber: number; role: PageRole; secondaryRoles: PageRole[]; confidence: number; evidence: PageEvidence[] }
export interface ProcedureDiscovery { procedureKey: string; category: 'SID' | 'STAR'; name: string; runways: string[]; navigationType?: string | null; primaryPages: number[]; relatedPages: number[]; sharedPages: number[]; confidence: number }
export interface AirportAnalysis { airport: { icao: string; iata?: string | null; name: string; country?: string | null }; document: { publisher?: string | null; effectiveDate?: string | null; languages: string[]; pageCount: number }; pageRoles: PageRoleResult[]; procedures: ProcedureDiscovery[]; sharedSources: number[]; unassignedPages: number[]; warnings: string[]; decisionSummary?: string }
export interface ProcedurePackage { packageId: string; procedureKey: string; category: 'SID' | 'STAR'; procedureName: string; runways: string[]; sources: { primaryCharts: number[]; procedureTables: number[]; coordinateTables: number[]; runwayPages: number[]; navaidPages: number[]; sharedNotes: number[]; profilePages: number[]; minimaPages: number[]; relatedPages: number[] }; confidence: number; warnings: string[]; manualRevision?: number }

export type DocumentParseStatus = 'UPLOADED' | 'PARSING' | 'PARSED' | 'FAILED';
export interface AipDocument { documentId: string; fileName: string; filePath: string; sizeBytes: number; pageCount: number; parseStatus: DocumentParseStatus; error?: string; createdAt: string }
export interface PackagePageRef { documentId: string; fileName: string; pageNumber: number; pageRole: string; secondaryRoles?: string[]; isShared: boolean; confidence: number }
export type SourcePresence = 'PRESENT' | 'MISSING' | 'AMBIGUOUS' | 'NOT_REQUIRED';
export type SourcePackageStatus = 'COMPLETE_SOURCE_SET' | 'CHART_MISSING' | 'TABLE_MISSING' | 'COORDINATE_MISSING' | 'SOURCE_AMBIGUOUS' | 'PROCEDURE_NOT_FOUND' | 'INSUFFICIENT_FOR_424' | 'INSUFFICIENT_FOR_GEOMETRY';
export interface PackageSourceCompleteness { chart: SourcePresence; table: SourcePresence; coordinates: SourcePresence; text: SourcePresence; runwayData: SourcePresence; navaidData: SourcePresence }
export interface PackagePreflightIssue { code: string; message: string; page?: number; procedure?: string }
export interface PackagePreflight { preflightPassed: boolean; checkedAt: string; blockingIssues: PackagePreflightIssue[]; warnings: PackagePreflightIssue[] }
export type PackageStatus = 'GROUPED' | 'PLANNING' | 'PLAN_COMPLETED' | 'RECOGNIZING' | 'VALIDATING' | 'COMPLETED' | 'COMPLETED_WITH_WARNINGS' | 'REQUIRES_REVIEW' | 'FAILED';
export type RecognitionAction = 'EXTRACT_PROCEDURE_METADATA' | 'EXTRACT_FIX_COORDINATES' | 'ANALYZE_ROUTE_STRUCTURE' | 'EXTRACT_PROCEDURE_LEGS' | 'EXTRACT_CONSTRAINTS' | 'EXTRACT_MINIMA' | 'EXTRACT_HOLDING' | 'BUILD_GEOJSON' | 'BUILD_ARINC_424_CANDIDATE' | 'VALIDATE_PROCEDURE_STRUCTURE' | 'VALIDATE_AGAINST_SOURCE_CHART';
export interface RecognitionPlan { packageId: string; procedureType: 'SID' | 'STAR' | 'APPROACH'; detectedStructure: { hasRunwayTransition: boolean; hasCommonRoute: boolean; hasEnrouteTransitions: boolean; hasMissedApproach: boolean; hasCoordinateTable: boolean; hasProcedureTable: boolean }; recognitionPlan: Array<{ sequence: number; action: RecognitionAction; sourcePages: Array<{ documentId: string; pageNumber: number }> }>; geometryStrategy: string; arinc424Strategy: string; requiredTools: string[]; risks: string[]; missingInformation: string[]; decisionSummary: string; promptVersion: string }
export interface BusinessProcedurePackage extends ProcedurePackage { procedureCategory: 'SID' | 'STAR' | 'APPROACH'; navigationType?: string | null; packagePages: PackagePageRef[]; groupingConfidence: number; groupingReason: string; status: PackageStatus; recognitionPlan?: RecognitionPlan; selected?: boolean; sourceCompleteness?: PackageSourceCompleteness; packageStatus?: SourcePackageStatus; preflight?: PackagePreflight }
export interface AirportPackageAnalysis { airport: { icao: string; name: string; country?: string | null }; packages: Array<{ procedureKey: string; procedureCategory: 'SID' | 'STAR' | 'APPROACH'; procedureName: string; runways: string[]; navigationType?: string | null; sources: Array<{ documentId: string; fileName: string; pages: number[]; roles: string[] }>; sharedSources: Array<{ documentId: string; fileName: string; pages: number[]; roles: string[] }>; groupingConfidence: number; groupingReason: string; warnings: string[] }>; unassignedPages: Array<{ documentId: string; pageNumber: number; reason: string }>; warnings: string[]; decisionSummary: string }

export type ProcedureCategory = 'SID' | 'STAR' | 'APPROACH';
export type ApproachType = 'ILS' | 'LOC' | 'RNP' | 'RNP_AR' | 'VOR' | 'NDB' | 'GLS' | 'VISUAL' | 'OTHER';
export type FixRole = 'IAF' | 'IF' | 'FAF' | 'FAP' | 'SDF' | 'MAPT' | 'MAHF' | 'DER' | 'NONE';
/**
 * 最低爬升梯度（PDG）。源页通常按程序整条发布一句，如
 * "MINIMUM CLIMB GRADIENT (PDG) 5% UNTIL PASSING 6000FT FOR ATC PURPOSES"，
 * 且同一张图上各条 SID 的数值可能不同（WMKJ 实测 PIMOK 1J 是 3500FT，其余 6000FT）。
 * 此前 PIR 完全没有这个字段——不是没提取到，而是没建模，于是它在源页上明明白白却无处安放。
 */
export interface ClimbGradient { percent?: number | null; untilAltitudeFt?: number | null; purpose?: string | null; rawText?: string | null }
export interface PirRoute { routeId: string; routeType: 'RUNWAY_TRANSITION' | 'COMMON_ROUTE' | 'ENROUTE_TRANSITION' | 'APPROACH_TRANSITION' | 'FINAL_APPROACH' | 'MISSED_APPROACH' | 'OTHER'; identifier: string; runway?: string | null; transitionFix?: string | null; climbGradient?: ClimbGradient | null; legIds: string[]; sequence: number }
export interface PirFix { fixId: string; identifier: string; type: string; role?: FixRole | null; latitude?: number | null; longitude?: number | null; coordinateSourceType: 'EXPLICIT_TABLE' | 'EXPLICIT_TEXT' | 'NAVAID_DATABASE' | 'RUNWAY_DATABASE' | 'DERIVED_COURSE_DISTANCE' | 'CHART_GEOREFERENCED' | 'AI_INFERRED' | 'UNRESOLVED'; coordinateAccuracyMeters?: number | null; evidence: string[]; confidence: number; status: FieldStatus; allowFor424?: boolean; derivation?: string | null }
export interface PirRunway { runwayId: string; designator: string; thresholdLatitude?: number | null; thresholdLongitude?: number | null; derLatitude?: number | null; derLongitude?: number | null; elevationFt?: number | null; thresholdCrossingHeightFt?: number | null; trueBearing?: number | null; evidence: string[]; status: FieldStatus }
export interface PirMinima { minimaId: string; type: 'DA' | 'MDA' | 'OCA' | 'OCH' | 'RVR' | 'VIS'; valueFt?: number | null; valueMeters?: number | null; aircraftCategory?: string | null; runway?: string | null; condition?: string | null; rawText?: string | null; evidence: string[]; status: FieldStatus }
export interface PirHolding { holdingFixId?: string | null; inboundCourse?: number | null; courseReference?: 'MAGNETIC' | 'TRUE'; turnDirection: 'L' | 'R'; legTimeMin?: number | null; legDistanceNm?: number | null; minimumAltitudeFt?: number | null; maximumAltitudeFt?: number | null; speedLimitKias?: number | null; rawText?: string | null }
export interface AltitudeConstraint { type: 'AT' | 'AT_OR_ABOVE' | 'AT_OR_BELOW' | 'BETWEEN' | 'NONE'; lowerFt?: number | null; upperFt?: number | null; rawText?: string | null }
export interface SpeedConstraint { type: 'AT' | 'AT_OR_ABOVE' | 'AT_OR_BELOW' | 'NONE'; valueKias?: number | null }
export interface PirLeg { legId: string; sequence: number; routeId: string; pathTerminator: string; fromFixId?: string | null; toFixId?: string | null; centerFixId?: string | null; recommendedNavaidId?: string | null; course?: number | null; courseReference: 'MAGNETIC' | 'TRUE'; distanceNm?: number | null; radiusNm?: number | null; turnDirection?: 'L' | 'R' | null; altitudeConstraint?: AltitudeConstraint | null; speedConstraint?: SpeedConstraint | null; verticalAngle?: number | null; holding?: PirHolding | null; openEnded: boolean; evidence: string[]; confidence: number; fieldStatus: Record<string, FieldStatus>; warnings: string[] }
export interface PirConflict { conflictId: string; fieldPath: string; reason?: string | null; status: 'OPEN' | 'RESOLVED'; candidates: Array<{ value: unknown; source: string; evidence: string[]; confidence?: number }> }
export interface ValidationResult { ruleCode: string; severity: 'INFO' | 'WARNING' | 'ERROR' | 'BLOCKER'; fieldPath: string; message: string; evidence: string[]; autoRepairable: boolean }
export interface ProcedurePIR { schemaVersion: '1.0.0' | '1.1.0'; airport: { icao: string; name?: string }; procedure: { category: ProcedureCategory; approachType?: ApproachType | null; identifier: string; name: string; runways: string[]; navigationSpecification?: string | null; effectiveDate?: string | null }; routes: PirRoute[]; fixes: PirFix[]; legs: PirLeg[]; runwayData: PirRunway[]; minima: PirMinima[]; notes: Array<{ text: string; evidence: string[] }>; sourceEvidence: PageEvidence[]; conflicts: PirConflict[]; validation: { results: ValidationResult[] }; quality: { confidence: number; reviewRequired: boolean; unresolvedFields: string[] } }
export interface AgentStep { stepId: string; name: string; status: StepStatus; startedAt?: string; completedAt?: string; durationMs?: number; input?: unknown; output?: unknown; error?: string; retryCount: number; version: number }
export interface ModelCall { callId: string; agentRunId: string; procedureId?: string; stepName: string; toolName?: string; toolArguments?: unknown; toolResultSummary?: string; startedAt: string; completedAt: string; tokenUsage?: { input?: number; output?: number }; model: string; error?: string; decisionSummary?: string; promptName: string; promptVersion: string; rawResponsePath?: string }
export interface AgentProcedure { procedureId: string; packageId: string; version: number; pir?: ProcedurePIR; geojson?: Record<string, unknown>; candidate424?: { status: '424_CONFIRMED' | '424_DERIVED' | '424_CANDIDATE' | '424_INCOMPLETE'; text: string; missingFields: string[]; roundTrip?: Record<string, unknown>; generatedBy?: 'AI' | 'COMPILER' | 'COMPILER_FALLBACK'; decisionSummary?: string; diffs?: Array<{ kind: string; code: string; detail: string }>; profile?: string }; validations: ValidationResult[]; status: 'PENDING' | 'RUNNING' | 'COMPLETED' | 'FAILED' }
/** 任务运行归属：谁在跑、心跳到哪一刻。落盘，因此跨进程可见。 */
export interface ActiveRun { owner: string; startedAt: string; heartbeatAt: string; description: string }
export interface AgentTask { activeRun?: ActiveRun | null; taskId: string; taskType: 'AGENT_AD2_RECOGNITION'; taskName: string; airportIcao?: string | null; airportName?: string | null; documents: AipDocument[]; fileName?: string; filePath?: string; status: TaskStatus; stage: 'UPLOAD' | 'ANALYZING' | 'PACKAGES_READY' | 'RECOGNIZING' | 'RESULTS_READY' | 'FAILED' | string; progress: number; currentProcedure?: string; completedProcedures: number; totalProcedures: number; warningCount: number; errorCount: number; createdAt: string; updatedAt: string; pages: PageAsset[]; airportAnalysis?: AirportAnalysis; packages: BusinessProcedurePackage[]; procedures: AgentProcedure[]; steps: AgentStep[]; modelCalls: ModelCall[]; error?: string; cancelRequested?: boolean }
