<script setup lang="ts">
import { onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { agentRequest, uploadForm } from '../../services/agentApi';
const router=useRouter();const tasks=ref<any[]>([]);const files=ref<File[]>([]);const taskName=ref('');const error=ref('');const creating=ref(false);const dragging=ref(false);const removing=ref('');
onMounted(load);async function load(){try{tasks.value=await agentRequest('/tasks');error.value=''}catch(e){error.value=message(e)}}
function select(list:FileList|null){if(!list)return;const seen=new Set(files.value.map(f=>`${f.name}:${f.size}`));for(const file of Array.from(list))if(file.type==='application/pdf'||file.name.toLowerCase().endsWith('.pdf')){const key=`${file.name}:${file.size}`;if(!seen.has(key)){files.value.push(file);seen.add(key)}}}
function drop(e:DragEvent){dragging.value=false;select(e.dataTransfer?.files||null)}
async function create(){if(!files.value.length)return;creating.value=true;error.value='';try{const task=await agentRequest<any>('/tasks',{method:'POST',body:uploadForm(files.value,{taskName:taskName.value||'机场航行数据生产任务'})});await router.push(`/production-tasks/${task.taskId}/intake`)}catch(e){error.value=message(e)}finally{creating.value=false}}
// 删除会连同该任务的全部页面渲染与产物一并消失，不可撤销，因此先二次确认。
// 此前任务只能新建不能删除，历史任务连同每份 PDF 的整套渲染页一直堆积（实测攒到 1.2GB）。
async function remove(task:any){
  if(!window.confirm(`删除任务「${task.taskName}」？该任务的页面渲染、识别结果与产物都会一并删除，无法恢复。`))return;
  removing.value=task.taskId;error.value='';
  try{await agentRequest(`/tasks/${task.taskId}`,{method:'DELETE'});await load()}
  catch(e){error.value=message(e)}
  finally{removing.value=''}
}
function message(e:unknown){return e instanceof Error?e.message:String(e)}
</script>
<template><main class="page"><header><div><p class="eyebrow">NAVIGATION DATA PRODUCTION</p><h1>机场航行数据生产</h1><p>批量组织AIP资料，自动生产结构化数据与424候选，只把例外留给专业人员。</p></div></header><p v-if="error" class="error">{{error}}</p><section class="create"><div class="copy"><h2>新建机场生产任务</h2><p>上传单机场PDF或选择国家文件夹。系统将建立程序清单、执行识别与确定性质量门，并集中列出待复核项。</p><input v-model="taskName" placeholder="生产任务名称（可选）"></div><div class="drop" :class="{dragging}" @dragover.prevent="dragging=true" @dragleave="dragging=false" @drop.prevent="drop"><strong>拖拽 PDF 或选择文件</strong><span>支持多选与文件夹</span><div><label>选择 PDF<input type="file" accept="application/pdf" multiple @change="select(($event.target as HTMLInputElement).files)"></label><label class="secondary">选择文件夹<input type="file" accept="application/pdf" multiple webkitdirectory="" @change="select(($event.target as HTMLInputElement).files)"></label></div></div><div v-if="files.length" class="queue"><div v-for="(file,index) in files" :key="file.name+file.size"><span>PDF</span><p><b>{{file.name}}</b><small>{{(file.size/1024/1024).toFixed(1)}} MB</small></p><button @click="files.splice(index,1)">移除</button></div><button class="primary" :disabled="creating" @click="create">{{creating?'正在创建…':`创建生产任务（${files.length} 个文件）`}}</button></div></section><section class="tasks"><div class="section-title"><h2>机场生产任务</h2><button @click="load">刷新</button></div><div v-if="tasks.length" class="task-list"><article v-for="task in tasks" :key="task.taskId"><div class="identity"><span class="status">{{task.stage}}</span><h3>{{task.taskName}}</h3><p>{{task.airport?.icao||'机场待识别'}} · {{task.fileCount}} 个 PDF · {{task.packageCount}} 个程序包</p></div><div class="production"><span><b>{{task.production?.autoPassPackages||0}}</b><small>自动通过</small></span><span class="review"><b>{{task.production?.reviewPackages||0}}</b><small>待复核</small></span><span class="blocked"><b>{{task.production?.blockedPackages||0}}</b><small>阻塞</small></span><span><b>{{task.production?.autoPassRate==null?'—':`${task.production.autoPassRate}%`}}</b><small>自动通过率</small></span></div><button class="enter" @click="router.push(task.stage==='UPLOAD'?`/production-tasks/${task.taskId}/intake`:`/production-tasks/${task.taskId}`)">进入生产任务</button><button class="remove" :disabled="removing===task.taskId" @click="remove(task)">{{removing===task.taskId?'删除中…':'删除'}}</button></article></div><p v-else class="empty">暂无机场生产任务</p></section></main></template>
<style scoped>.page{padding:34px;max-width:1320px;margin:auto;color:#102a43}.eyebrow{font-size:12px;letter-spacing:.15em;color:#1769e0;font-weight:700}h1{font-size:34px;margin:4px 0}header p{color:#627d98}.error{background:#fee2e2;color:#991b1b;padding:12px;border-radius:8px}.create{margin-top:24px;background:#fff;border-radius:16px;padding:28px;box-shadow:0 8px 30px #102a4310;display:grid;grid-template-columns:.8fr 1.2fr;gap:28px}.copy p{color:#627d98;line-height:1.7}.copy input{width:100%;box-sizing:border-box;padding:11px;border:1px solid #ccd6e0;border-radius:8px}.drop{border:2px dashed #b8c7d9;border-radius:14px;min-height:190px;display:grid;place-content:center;text-align:center;gap:8px;background:#f8fbff}.drop.dragging{border-color:#1769e0;background:#edf5ff}.drop span{color:#829ab1}.drop label{display:inline-block;background:#1769e0;color:#fff;padding:9px 14px;border-radius:8px;margin:8px 4px;cursor:pointer}.drop label.secondary{background:#fff;color:#174ea6;border:1px solid #aac4e6}.drop input{display:none}.queue{grid-column:1/-1}.queue>div{display:flex;align-items:center;border-top:1px solid #edf1f5;padding:10px}.queue>div>span{background:#e8f1ff;color:#174ea6;padding:7px;border-radius:6px}.queue p{flex:1;margin:0 12px}.queue small{display:block;color:#829ab1}.queue button,.section-title button{border:0;background:none;color:#52606d;cursor:pointer}.primary,.enter{border:0;background:#1769e0;color:#fff;border-radius:8px;padding:11px 16px;cursor:pointer}.remove{border:0;background:none;color:#a02c2c;cursor:pointer;padding:11px 10px;margin-left:6px}.remove:disabled{color:#b8c7d9;cursor:default}.tasks{margin-top:34px}.section-title{display:flex;justify-content:space-between}.task-list{display:grid;gap:12px}.task-list article{display:flex;align-items:center;background:#fff;border-radius:12px;padding:18px 22px;gap:18px}.identity{min-width:290px}.task-list h3{margin:5px 0}.task-list p{color:#627d98;margin:0}.status{font-size:11px;color:#1769e0;background:#edf5ff;padding:4px 7px;border-radius:5px}.production{display:grid;grid-template-columns:repeat(4,minmax(70px,1fr));text-align:center;margin-left:auto;gap:5px}.production span{padding:6px 10px;border-left:1px solid #edf1f5}.production b,.production small{display:block}.production b{font-size:17px}.production small{color:#829ab1;white-space:nowrap}.production .review b{color:#a16207}.production .blocked b{color:#b42318}.empty{text-align:center;color:#829ab1;padding:40px}@media(max-width:980px){.task-list article{align-items:flex-start;flex-wrap:wrap}.production{order:3;width:100%;margin:0}.enter{margin-left:auto}}@media(max-width:800px){.create{grid-template-columns:1fr}.page{padding:18px}}</style>
