<script setup lang="ts">
import { onMounted,ref } from 'vue';import {useRoute,useRouter} from 'vue-router';import WorkflowSteps from '../../components/agent/WorkflowSteps.vue';import {agentRequest,uploadForm} from '../../services/agentApi';
const route=useRoute(),router=useRouter();const id=String(route.params.taskId);const task=ref<any>();const error=ref('');const busy=ref(false);const append=ref<File[]>([]);onMounted(load);async function load(){try{task.value=await agentRequest(`/tasks/${id}`)}catch(e){error.value=msg(e)}}
async function add(){if(!append.value.length)return;busy.value=true;try{await agentRequest(`/tasks/${id}/documents`,{method:'POST',body:uploadForm(append.value)});append.value=[];await load()}catch(e){error.value=msg(e)}finally{busy.value=false}}
async function remove(doc:string){try{await agentRequest(`/tasks/${id}/documents/${doc}`,{method:'DELETE'});await load()}catch(e){error.value=msg(e)}}
async function analyze(){busy.value=true;try{await agentRequest(`/tasks/${id}/analyze`,{method:'POST'});router.push(`/agent-tasks/${id}/packages`)}catch(e){error.value=msg(e)}finally{busy.value=false}}function choose(list:FileList|null){append.value=Array.from(list||[]).filter(f=>f.name.toLowerCase().endsWith('.pdf'))}function msg(e:unknown){return e instanceof Error?e.message:String(e)}
</script>
<template><main v-if="task" class="page"><WorkflowSteps :current="0"/><header><button @click="router.push('/autonomous-recognition')">← 所有任务</button><div><h1>{{task.taskName}}</h1><p>上传和确认该机场的全部 AD-2 文件，再交给 AI 统一分析。</p></div></header><p v-if="error" class="error">{{error}}</p><section class="panel"><div class="heading"><div><h2>机场文件</h2><p>共 {{task.documents.length}} 个 PDF</p></div><label>追加 PDF<input type="file" accept="application/pdf" multiple @change="choose(($event.target as HTMLInputElement).files)"></label></div><div class="documents"><article v-for="doc in task.documents" :key="doc.documentId"><span>PDF</span><div><b>{{doc.fileName}}</b><p>{{(doc.sizeBytes/1024/1024).toFixed(1)}} MB · {{doc.pageCount||'—'}} 页</p></div><em :class="doc.parseStatus">{{doc.parseStatus}}</em><button v-if="task.stage==='UPLOAD'" @click="remove(doc.documentId)">删除</button></article></div><div v-if="append.length" class="append"><p>待追加：{{append.map(f=>f.name).join('、')}}</p><button @click="add">确认追加</button></div></section><footer><p>AI 将读取全部文件，识别文件间关联并创建跨文件程序包。</p><button class="primary" :disabled="busy||!task.documents.length" @click="analyze">{{busy?'正在提交…':'开始 AI 程序包分组'}}</button></footer></main></template>
<style scoped>.page{max-width:1180px;margin:auto;padding:30px;color:#102a43}header{display:flex;gap:20px;margin:35px 0}header button{border:0;background:none;color:#52606d}h1{margin:0}header p,.heading p,footer p{color:#627d98}.error{background:#fee2e2;color:#991b1b;padding:12px}.panel{background:#fff;padding:26px;border-radius:14px}.heading{display:flex;justify-content:space-between;align-items:center}.heading label,.primary,.append button{background:#1769e0;color:#fff;border:0;padding:10px 15px;border-radius:8px;cursor:pointer}.heading input{display:none}.documents article{display:flex;align-items:center;gap:14px;border-top:1px solid #edf1f5;padding:16px}.documents article>span{background:#e8f1ff;color:#174ea6;padding:10px;border-radius:7px}.documents article div{flex:1}.documents p{margin:5px 0 0;color:#829ab1}.documents em{font-style:normal;font-size:12px;padding:5px 8px;border-radius:5px;background:#edf1f5}.documents em.PARSED{background:#e6f6ed;color:#237a4b}.documents button{border:0;background:none;color:#b42318}.append{display:flex;justify-content:space-between;align-items:center;background:#f3f7fb;padding:12px}footer{display:flex;justify-content:space-between;align-items:center;margin-top:22px}.primary{font-size:15px}</style>
