-- PostgreSQL 15+. The engine currently also supports JSON-file persistence for zero-setup local runs.
CREATE TABLE IF NOT EXISTS agent_recognition_tasks (id uuid PRIMARY KEY, task_type text NOT NULL, status text NOT NULL, stage text NOT NULL, progress integer NOT NULL DEFAULT 0, source_file_name text NOT NULL, source_file_path text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), error jsonb);
CREATE TABLE IF NOT EXISTS agent_task_steps (id uuid PRIMARY KEY, task_id uuid NOT NULL REFERENCES agent_recognition_tasks(id), name text NOT NULL, status text NOT NULL, version integer NOT NULL DEFAULT 1, retry_count integer NOT NULL DEFAULT 0, input jsonb, output jsonb, error jsonb, started_at timestamptz, completed_at timestamptz);
CREATE TABLE IF NOT EXISTS aip_documents (id uuid PRIMARY KEY, source_name text NOT NULL, storage_path text NOT NULL, sha256 text, page_count integer, metadata jsonb NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS aip_document_pages (id uuid PRIMARY KEY, document_id uuid NOT NULL REFERENCES aip_documents(id), page_number integer NOT NULL, role text, native_text text, spans jsonb, vector_paths jsonb, assets jsonb, quality jsonb, UNIQUE(document_id,page_number));
CREATE TABLE IF NOT EXISTS airport_analysis_results (id uuid PRIMARY KEY, task_id uuid NOT NULL REFERENCES agent_recognition_tasks(id), version integer NOT NULL, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS procedure_packages (id uuid PRIMARY KEY, task_id uuid NOT NULL REFERENCES agent_recognition_tasks(id), procedure_key text NOT NULL, category text NOT NULL, name text NOT NULL, version integer NOT NULL DEFAULT 1, result jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS procedure_package_pages (package_id uuid NOT NULL REFERENCES procedure_packages(id), page_id uuid NOT NULL REFERENCES aip_document_pages(id), source_role text NOT NULL, PRIMARY KEY(package_id,page_id,source_role));
CREATE TABLE IF NOT EXISTS procedures (id uuid PRIMARY KEY, package_id uuid NOT NULL REFERENCES procedure_packages(id), version integer NOT NULL, status text NOT NULL, pir jsonb NOT NULL, quality jsonb, UNIQUE(package_id,version));
CREATE TABLE IF NOT EXISTS procedure_routes (id uuid PRIMARY KEY, procedure_id uuid NOT NULL REFERENCES procedures(id), data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS procedure_fixes (id uuid PRIMARY KEY, procedure_id uuid NOT NULL REFERENCES procedures(id), identifier text NOT NULL, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS procedure_legs (id uuid PRIMARY KEY, procedure_id uuid NOT NULL REFERENCES procedures(id), route_id uuid, sequence integer NOT NULL, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS procedure_field_evidence (id uuid PRIMARY KEY, procedure_id uuid NOT NULL REFERENCES procedures(id), field_path text NOT NULL, page_id uuid, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS procedure_conflicts (id uuid PRIMARY KEY, procedure_id uuid NOT NULL REFERENCES procedures(id), field_path text NOT NULL, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS procedure_validation_results (id uuid PRIMARY KEY, procedure_id uuid NOT NULL REFERENCES procedures(id), rule_code text NOT NULL, severity text NOT NULL, data jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS procedure_geojson_versions (id uuid PRIMARY KEY, procedure_id uuid NOT NULL REFERENCES procedures(id), version integer NOT NULL, geojson jsonb NOT NULL, UNIQUE(procedure_id,version));
CREATE TABLE IF NOT EXISTS procedure_424_versions (id uuid PRIMARY KEY, procedure_id uuid NOT NULL REFERENCES procedures(id), version integer NOT NULL, status text NOT NULL, candidate_text text, mapping jsonb, round_trip jsonb, UNIQUE(procedure_id,version));
CREATE TABLE IF NOT EXISTS agent_model_calls (id uuid PRIMARY KEY, task_id uuid NOT NULL REFERENCES agent_recognition_tasks(id), procedure_id uuid, step_name text NOT NULL, prompt_name text NOT NULL, prompt_version text NOT NULL, model text NOT NULL, request jsonb, response_path text, usage jsonb, error jsonb, started_at timestamptz NOT NULL, completed_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS manual_review_records (id uuid PRIMARY KEY, procedure_id uuid NOT NULL REFERENCES procedures(id), field_path text NOT NULL, previous_value jsonb, reviewed_value jsonb, reviewer text, created_at timestamptz NOT NULL DEFAULT now());
