import assert from 'node:assert/strict';
import test from 'node:test';
import { buildAirportBatchStatus } from '../recognition-v2/orchestration/airportBatchStatus';
import { createInitialManifest, failStage, startStage } from '../recognition-v2/orchestration/stateMachine';
import type { PublicationLedger } from '../recognition-v2/contracts/index';

function run(packageId: string) {
  return createInitialManifest({ taskId: 'task', packageId, runId: `run-${packageId}`, sourcePackageHash: 'hash', now: '2026-07-17T00:00:00.000Z' });
}

test('airport batch status survives page refresh by deriving package state from persisted manifests and ledgers', () => {
  const failed = failStage(startStage(run('failed'), 'PAGE_LAYOUT', { inputHash: 'input', now: '2026-07-17T00:00:01.000Z' }), 'PAGE_LAYOUT', {
    code: 'MODEL_CONTRACT', message: 'model schema contract validation failed', retryable: true, now: '2026-07-17T00:00:02.000Z',
  });
  const ledger: PublicationLedger = {
    version: 1, activeReleaseId: 'release-1', updatedAt: '2026-07-17T00:00:03.000Z',
    releases: [{ releaseId: 'release-1', runId: 'published-run', artifactRef: 'artifacts/release.json', canonicalHash: 'a', textHash: 'b', status: 'ACTIVE', publishedAt: '2026-07-17T00:00:03.000Z' }],
  };
  const status = buildAirportBatchStatus('task', [
    { packageId: 'new', packageName: 'New', runs: [] },
    { packageId: 'failed', packageName: 'Failed', runs: [failed] },
    { packageId: 'published', packageName: 'Published', runs: [], ledger },
  ], '2026-07-17T00:00:04.000Z');
  assert.equal(status.notStartedCount, 1);
  assert.equal(status.needsOptimizationCount, 1);
  assert.equal(status.activeReleaseCount, 1);
  assert.equal(status.packages.find((item) => item.packageId === 'failed')?.issue?.category, 'MODEL_OUTPUT');
  assert.equal(status.packages.find((item) => item.packageId === 'published')?.state, 'PUBLISHED');
});

test('unresolved review is reported as a software optimization item instead of silent manual work', () => {
  const reviewRun = { ...run('review'), status: 'REVIEW_REQUIRED' as const };
  const status = buildAirportBatchStatus('task', [{ packageId: 'review', packageName: 'Review', runs: [reviewRun], pendingReviewCount: 7 }]);
  const item = status.packages[0];
  assert.equal(item.state, 'NEEDS_OPTIMIZATION');
  assert.equal(item.issue?.phase, 'HUMAN_REVIEW');
  assert.match(item.issue?.message ?? '', /7/);
});

test('an active release generated by an older encoder is queued for safe republishing', () => {
  const completed = { ...run('published'), status: 'COMPLETED' as const };
  const ledger: PublicationLedger = {
    version: 1, activeReleaseId: 'release-1', updatedAt: '2026-07-17T00:00:03.000Z',
    releases: [{ releaseId: 'release-1', runId: completed.runId, artifactRef: 'artifacts/release.json', canonicalHash: 'a', textHash: 'old', status: 'ACTIVE', publishedAt: '2026-07-17T00:00:03.000Z' }],
  };
  const status = buildAirportBatchStatus('task', [{ packageId: 'published', packageName: 'Published', runs: [completed], ledger, activeReleaseStale: true }]);
  assert.equal(status.readyToPublishCount, 1);
  assert.equal(status.packages[0].state, 'READY_TO_PUBLISH');
  assert.equal(status.activeReleaseCount, 1);
});
